//! **A manifest note for a program this tree did not write** (milestone 595 (the shell runs a `std`
//! program), 2026-10-07 (UTC)). Name: provisional, `cargo xtask foreign-note`.
//!
//! A program run by its path is endowed from the manifest note in its own bytes (milestone 597 (a
//! program carries its manifest in an ELF note), DECISIONS §197 (a package is one archive file) option M2). An in-tree program
//! carries one with `manifest_note::carry!`. `ripgrep` is unmodified source from crates.io, so it
//! cannot, and with no note the shell runs it as a native program that hears no words, which a `std`
//! program cannot survive. This writes the note as a relocatable object of its own, which
//! `helpers/build-ripgrep.sh` passes to the link (`-Clink-arg=<object>`). The shared link script
//! keeps every `.note.nife.*` input section in the `PT_NOTE`, so the note lands where the readers
//! look and the program's source stays untouched. #1319 measured this route first.
//!
//! The manifest is [`grant_plan::UNVOUCHED_STD_MANIFEST`], and only that: a `std` program that hears
//! its line and reads what its words name, read-only. That is what an unvouched program is endowed
//! with whatever it declares, so declaring more would only be refused (`ImageRefusal::ExceedsVouch`).
//! Declaring exactly the vouch is also what `std_grep`'s note does.
//!
//! **Why `rustc` and not hand-written ELF.** The object is a `#![no_std]` crate with one static,
//! compiled for the bare-metal target of the same ISA, whose `core` the pinned toolchain already
//! ships (`rust-toolchain.toml`'s `targets`). That leaves the object's header, and on riscv64 its
//! float-ABI flags, to the compiler that knows them. `riscv64imac-unknown-none-elf` is `lp64` with
//! `C`, as `targets/riscv64-unknown-nife.json` is, so `lld` accepts the mix. The bytes themselves
//! come from `manifest_note::Note::of`, the same function `carry!` expands to, so there is one
//! encoder.

use std::path::Path;

/// The bare-metal triple whose object `lld` will link into a program built for `nife_triple`.
fn bare_triple(nife_triple: &str) -> Option<&'static str> {
    match nife_triple {
        "aarch64-unknown-nife" => Some("aarch64-unknown-none-softfloat"),
        "riscv64-unknown-nife" => Some("riscv64imac-unknown-none-elf"),
        "x86_64-unknown-nife" => Some("x86_64-unknown-none"),
        _ => None,
    }
}

/// The crate the object is compiled from.
fn source() -> String {
    let note = manifest_note::Note::of(&grant_plan::UNVOUCHED_STD_MANIFEST);
    let bytes: Vec<String> = note.0.iter().map(|b| format!("{b:#04x}")).collect();
    format!(
        "// Generated by `cargo xtask foreign-note` (xtask/src/foreign_note.rs). Do not edit.\n\
         #![no_std]\n\
         #[repr(C, align(4))]\n\
         pub struct Note([u8; {len}]);\n\
         #[used]\n\
         #[unsafe(link_section = \".note.nife.manifest\")]\n\
         static NIFE_MANIFEST_NOTE: Note = Note([{bytes}]);\n",
        len = note.0.len(),
        bytes = bytes.join(", "),
    )
}

/// `cargo xtask foreign-note <nife-triple> <out.o>`.
pub(crate) fn foreign_note(triple: Option<String>, out: Option<String>) -> bool {
    let (Some(triple), Some(out)) = (triple, out) else {
        eprintln!("usage: cargo xtask foreign-note <aarch64|riscv64|x86_64>-unknown-nife <out.o>");
        return false;
    };
    let Some(bare) = bare_triple(&triple) else {
        eprintln!("foreign-note: no bare-metal twin for {triple}");
        return false;
    };
    let out = Path::new(&out);
    let src = out.with_extension("rs");
    if let Err(e) = std::fs::write(&src, source()) {
        eprintln!("foreign-note: {}: {e}", src.display());
        return false;
    }
    let ok = std::process::Command::new("rustc")
        .args(["--edition", "2024", "--crate-type", "lib", "--crate-name"])
        .arg("nife_foreign_manifest_note")
        .args([
            "--emit",
            "obj",
            "-C",
            "panic=abort",
            "-C",
            "codegen-units=1",
        ])
        .args(["--target", bare, "-o"])
        .arg(out)
        .arg(&src)
        .status()
        .is_ok_and(|s| s.success());
    if ok {
        eprintln!(
            "foreign-note: {} carries grant_plan::UNVOUCHED_STD_MANIFEST",
            out.display()
        );
    }
    ok
}
